# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comm_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('comm_type', models.CharField(choices=[('Inventory', 'Inventory'), ('Chemo', 'Chemo'), ('Operation', 'Operation'), ('HomeIV', 'HOMEIV'), ('POM', 'PtMed')], default='OPS', max_length=10)),
                ('descr', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='resolved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_item_resolved', to='staffcom.Comm_Item'),
        ),
    ]
