# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='resolved',
        ),
        migrations.AddField(
            model_name='comm_item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='archive',
        ),
    ]
