# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffcom', '0002_auto_20171226_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comm_item',
            name='comm_type',
            field=models.CharField(choices=[('Inventory', 'Inventory'), ('Chemo', 'Chemo'), ('Operation', 'Operation'), ('HomeIV', 'HOMEIV')], default='OPS', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='link_to_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffcom.Comm_Item'),
        ),
    ]
