# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffcom', '0003_auto_20171228_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link_to_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='staffcom.Comm_Item'),
        ),
    ]
