# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffcom', '0004_auto_20171228_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('license', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comm_item',
            name='descr',
            field=models.TextField(help_text='<br/>Be as DESCRIPTIVE as possible [WHO, WHAT, WHEN, WHERE]'),
        ),
        migrations.AlterField(
            model_name='comm_item',
            name='title',
            field=models.CharField(help_text='<br/>This could be drug name, or shift name, refer to guidelines of use.', max_length=200, unique=True),
        ),
    ]
