# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffcom', '0005_auto_20171229_0745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
